$axure.loadCurrentPage({
  "url":"docentes.html",
  "generationDate":new Date(1397091242465.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bc539260e594b23846338355f6c93df",
    "type":"Axure:Page",
    "name":"Docentes",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c7e833a583f94fd19525916f0299d019",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":67},
            "size":{
              "width":559,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a98e30903cb46d2a8c41be85eb83702",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":559,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df1b1cd20d984ab09886ae723f5b3a79",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"080ed337f55e4772b6ba05887a57ae16",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":166,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/princiopal/u2.png"}},
{
                  "id":"26f9a4300f7945e79b24763f740c2a84",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":166,
                      "y":0},
                    "size":{
                      "width":193,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f94ecfe23ec8488fb4d00bfd273b9506",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":166,
                          "y":0},
                        "size":{
                          "width":193,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/princiopal/u4.png"}},
{
                  "id":"31e625df78a6494e812cc92f05104aac",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":359,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bff2f024b03e4620ab4e23ea9a66536d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":359,
                          "y":0},
                        "size":{
                          "width":200,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/princiopal/u6.png"}}]},
{
              "id":"2b42c767e073439389218f7b5ff73530",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":164,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e9f65445b1e482fbb629e82de8d9f79",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":164,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a3fe4e082304da9ace1a66de68aab70",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":164,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d9d2a4e8775c4adda969e74e83a42908",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":164,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u10.png"}},
{
                      "id":"bbe582bfd7a54aba887703bb6bcb3370",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":164,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"02bd3b6dc8b84c21ba371539d3f6b0e1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":164,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u12.png"}}]}],
              "parentCellId":"df1b1cd20d984ab09886ae723f5b3a79"},
{
              "id":"4bbfd2b5b1a54a849b789bebf76aee79",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":166,
                  "y":30},
                "size":{
                  "width":192,
                  "height":60},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb818fc0d0d948b18ed112c2ab9e844b",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":192,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1635176acbb4c9f9c32a587d95611bf",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":192,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2dbdac2ddfb94d0fa662513b95a65def",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":192,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u16.png"}},
{
                      "id":"c161d5d2eddc4a7f8c447fcb3e272d66",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":192,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"816c33457b8143159d20ebd37e41bd92",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":40},
                            "size":{
                              "width":192,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u18.png"}},
{
                      "id":"cfec17eb2b734722b8c851b2c7d4cb07",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":192,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c5aebb83632d47cbb8ab082259520297",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":192,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u16.png"}}]}],
              "parentCellId":"26f9a4300f7945e79b24763f740c2a84"},
{
              "id":"0c5b51f6572b4df6a9c31c61ced56467",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":359,
                  "y":30},
                "size":{
                  "width":199,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b9fc8fcaa084bc8b30077ba14080e6f",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":199,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7e51dccb1c64edc86490e0e8ef18108",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":199,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6fc5384d965148e899490889201f74a6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":199,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u24.png"}},
{
                      "id":"68b6dcb22f634d60b1813c94835b7bfe",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":199,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"918d4af7510946b0ae847c5fd92ef14d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":199,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/princiopal/u22.png"}}]}],
              "parentCellId":"31e625df78a6494e812cc92f05104aac"}]},
{
          "id":"aabb26c3250640c29dda323ee704aa14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed Bold', 'Bernard MT'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":90,
              "y":14},
            "size":{
              "width":303,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"326f69af97754f2cbbc03beffb8c4113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed Bold', 'Bernard MT'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":90,
                  "y":14},
                "size":{
                  "width":303,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9648531ca12c42f987657e025e9074db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":170},
            "size":{
              "width":720,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e805dd08f104b9da0cf670f911ce686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":170},
                "size":{
                  "width":720,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/docentes/u30.png"}},
{
          "id":"90e37d92517a43c69b79c8c8a2304a91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed Bold', 'Bernard MT'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":97,
              "y":170},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2369739935f04cb5ab8d382a9e2ed938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed Bold', 'Bernard MT'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":97,
                  "y":170},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1322c9e2ce5a4161a0fd228e00b4e307",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":230},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1b01ddcbc9c74f5096ad91257f53b8bc",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":220},
            "size":{
              "width":200,
              "height":170}},
          "adaptiveStyles":{
}},
{
          "id":"8d3f01aa19f44918aab3e404c7a6e9de",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":440},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c7e833a583f94fd19525916f0299d019":{
      "scriptId":"u0"},
    "3a98e30903cb46d2a8c41be85eb83702":{
      "scriptId":"u1"},
    "df1b1cd20d984ab09886ae723f5b3a79":{
      "scriptId":"u2"},
    "080ed337f55e4772b6ba05887a57ae16":{
      "scriptId":"u3"},
    "26f9a4300f7945e79b24763f740c2a84":{
      "scriptId":"u4"},
    "f94ecfe23ec8488fb4d00bfd273b9506":{
      "scriptId":"u5"},
    "31e625df78a6494e812cc92f05104aac":{
      "scriptId":"u6"},
    "bff2f024b03e4620ab4e23ea9a66536d":{
      "scriptId":"u7"},
    "2b42c767e073439389218f7b5ff73530":{
      "scriptId":"u8"},
    "5e9f65445b1e482fbb629e82de8d9f79":{
      "scriptId":"u9"},
    "5a3fe4e082304da9ace1a66de68aab70":{
      "scriptId":"u10"},
    "d9d2a4e8775c4adda969e74e83a42908":{
      "scriptId":"u11"},
    "bbe582bfd7a54aba887703bb6bcb3370":{
      "scriptId":"u12"},
    "02bd3b6dc8b84c21ba371539d3f6b0e1":{
      "scriptId":"u13"},
    "4bbfd2b5b1a54a849b789bebf76aee79":{
      "scriptId":"u14"},
    "bb818fc0d0d948b18ed112c2ab9e844b":{
      "scriptId":"u15"},
    "cfec17eb2b734722b8c851b2c7d4cb07":{
      "scriptId":"u16"},
    "c5aebb83632d47cbb8ab082259520297":{
      "scriptId":"u17"},
    "d1635176acbb4c9f9c32a587d95611bf":{
      "scriptId":"u18"},
    "2dbdac2ddfb94d0fa662513b95a65def":{
      "scriptId":"u19"},
    "c161d5d2eddc4a7f8c447fcb3e272d66":{
      "scriptId":"u20"},
    "816c33457b8143159d20ebd37e41bd92":{
      "scriptId":"u21"},
    "0c5b51f6572b4df6a9c31c61ced56467":{
      "scriptId":"u22"},
    "1b9fc8fcaa084bc8b30077ba14080e6f":{
      "scriptId":"u23"},
    "68b6dcb22f634d60b1813c94835b7bfe":{
      "scriptId":"u24"},
    "918d4af7510946b0ae847c5fd92ef14d":{
      "scriptId":"u25"},
    "f7e51dccb1c64edc86490e0e8ef18108":{
      "scriptId":"u26"},
    "6fc5384d965148e899490889201f74a6":{
      "scriptId":"u27"},
    "aabb26c3250640c29dda323ee704aa14":{
      "scriptId":"u28"},
    "326f69af97754f2cbbc03beffb8c4113":{
      "scriptId":"u29"},
    "9648531ca12c42f987657e025e9074db":{
      "scriptId":"u30"},
    "8e805dd08f104b9da0cf670f911ce686":{
      "scriptId":"u31"},
    "90e37d92517a43c69b79c8c8a2304a91":{
      "scriptId":"u32"},
    "2369739935f04cb5ab8d382a9e2ed938":{
      "scriptId":"u33"},
    "1322c9e2ce5a4161a0fd228e00b4e307":{
      "scriptId":"u34"},
    "1b01ddcbc9c74f5096ad91257f53b8bc":{
      "scriptId":"u35"},
    "8d3f01aa19f44918aab3e404c7a6e9de":{
      "scriptId":"u36"}}});